title: AMCL_DocTemplate
author: MWMathis Lab
logo: docs/images/zebra.png

execute:
  execute_notebooks: "off"

html:
  extra_navbar: ""
  use_issues_button: true
  use_repository_button: true
  extra_footer: |
    <div>Powered by <a href="https://jupyterbook.org/">Jupyter Book</a>.</div>

repository:
  url: https://github.com/AdaptiveMotorControlLab/CEBRA-lens
  path_to_book: docs
  branch: main

launch_buttons:
  colab_url: "https://colab.research.google.com/github/AdaptiveMotorControlLab/demos/usage_demo.ipynb"
